config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
  end
  resources :reviews, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

  validates :name, presence: true
  validates :address, presence: { message: "Le champs adresse ne peut pas être vide." }
  validates :category, presence: true, inclusion: { in: CATEGORIES, message: "%{value} n'est pas une catégorie valide" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true,
    numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 5,
    message: "doit être un entier entre 0 et 5"
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    restaurant = Restaurant.new(restaurant_params)
    restaurant.save
    redirect_to restaurants_path
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_restaurant, only: %i[new create]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end


  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

    <div>
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number %>
  </div>

  <div>
    <%= f.label :category %>
    <%= f.select :category, Restaurant::CATEGORIES %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container mt-5">
  <h1>Edit a restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <hr>
  <%= link_to restaurants_path, class: 'btn btn-light btn-sm border' do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to restaurant list
  <% end %>
</div>

app/views/restaurants/index.html.erb
<div class="container mt-5">
  <h1>Restaurants</h1>

  <ul id="restaurants">
    <% @restaurants.each do |restaurant| %>
      <li>
        <%= link_to restaurant.name, restaurant_path(restaurant.id) %>
        <%= link_to restaurant_path(restaurant.id), data: {turbo_method: :delete, turbo_confirm: "Delete #{restaurant.name}?"} do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>
      </li>
    <% end %>
  </ul>

  <hr>

  <%= link_to new_restaurant_path, class: 'btn btn-light btn-sm border' do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Add a new restaurant
  <% end %>

</div>

app/views/restaurants/new.html.erb
<div class="container mt-5">
  <h1>New restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <hr>
  <%= link_to restaurants_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-5">
  <div class="mb-4">

    <h1><%= @restaurant.name %></h1>
    <p>Address: <%= @restaurant.address %></p>
    <p>Phone number: <%= @restaurant.phone_number %></p>
    <p>Category: <%= @restaurant.category %></p>

    <%= link_to edit_restaurant_path(@restaurant.id), class: 'btn btn-light btn-sm border' do %>
      <i class="fa fa-pencil"></i> Edit this restaurant
    <% end %>

    <%= link_to restaurants_path, class: 'btn btn-light btn-sm border' do %>
      <i class="fa-solid fa-arrow-rotate-left"></i> Back to restaurant list
    <% end %>

    <ul>
      <% @reviews.each do |review| %>
        <li><%= review.content %> – Rating: <%= review.rating %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="container mt-5">
    <h3>Let a review to "<%= @restaurant.name %>"</h3>
      <%= simple_form_for [@restaurant, Review.new] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating %>
        <%= f.submit "Submit" %>
      <% end %>
</div>